m0t = new Array(13)               ; m0v = new Array(13)     ; m0s=12;
m1t = new Array(9)                ; m1v = new Array(9)      ; m1s=8;
m2t = new Array(48)               ; m2v = new Array(48)     ; m2s=47;
m3t = new Array(14)               ; m3v = new Array(14)     ; m3s=13;
m4t = new Array(12)               ; m4v = new Array(12)     ; m4s=11;

m0t [0] ="-----------------"      ; m0v [0] ="bos"; 
m0t [1] ="Ana Sayfa"              ; m0v [1] ="anasayfa.htm"; 
m0t [2] ="Yenilikler"             ; m0v [2] ="yenilikler.htm";
m0t [3] ="Agarta Nedir?"          ; m0v [3] ="agarta.htm";
m0t [4] ="-----------------"      ; m0v [4] ="bos";
m0t [5] ="Alternatif Þifa"        ; m0v [5] ="m1";
m0t [6] ="Öðretiler"              ; m0v [6] ="m2";
m0t [7] ="Ruhsal Mesajlar"        ; m0v [7] ="m3";
m0t [8] ="Makaleler"              ; m0v [8] ="m4";
m0t [9] ="-----------------"      ; m0v [9] ="bos";
m0t [10] ="KÝTAP ARÞÝVÝ"          ; m0v [10] ="kitaplar/index.html";
m0t [11] ="LÝNKLER"               ; m0v [11] ="linkler.htm";
m0t [12] ="son"                   ; m0v [12] ="son";

m1t [0] ="Alternatif Þifa"        ; m1v [0] ="m1"; 
m1t [1] ="-----------------"      ; m1v [1] ="bos";
m1t [2] ="Reiki"                  ; m1v [2] ="sr.htm";
m1t [3] ="Renk Terapisi"          ; m1v [3] ="bos";
m1t [4] ="Hemoterapi"             ; m1v [4] ="bos";
m1t [5] ="Meditasyon"             ; m1v [5] ="bos";
m1t [6] = "-----------------"     ; m1v [6] ="bos";
m1t [7] ="<-----"                 ; m1v [7] ="m0";
m1t [8] ="son"                    ; m1v [8] ="son";


m2t [0] ="ÖÐRETÝLER"                     ; m2v [0] ="bos";
m2t [1] ="---------------------------"   ; m2v [1] ="bos";
m2t [2] ="Aetherius"                     ; m2v [2] ="o_aet.htm";
m2t [3] ="Ahmediye"                      ; m2v [3] ="o_ahm.htm";
m2t [4] ="Alevilik"                      ; m2v [4] ="o_ale.htm";
m2t [5] ="Ananda Marga"                  ; m2v [5] ="o_ana.htm";
m2t [6] ="Bagavan Þiri Racniþ"           ; m2v [6] ="o_bag.htm";
m2t [7] ="Bahailik"                      ; m2v [7] ="o_bah.htm";
m2t [8] ="Bogomiller"                    ; m2v [8] ="o_bog.htm";
m2t [9] ="Budizm"                        ; m2v [9] ="o_bud.htm";
m2t [10] ="Children of God"              ; m2v [10] ="o_cog.htm";
m2t [11] ="College Of Uni. Wisdom"       ; m2v [11] ="o_couw.htm";
m2t [12] ="Dionisos Kültü"               ; m2v [12] ="o_dio.htm";
m2t [13] ="Ekankar"                      ; m2v [13] ="o_eka.htm";
m2t [14] ="Eleusis Kültü"                ; m2v [14] ="o_ele.htm";
m2t [15] ="Ezoterizm"                    ; m2v [15] ="o_ezo.htm";
m2t [16] ="Gnostizm"                     ; m2v [16] ="o_gno.htm";
m2t [17] ="Gülhaç"                       ; m2v [17] ="o_gul.htm";
m2t [18] ="Hermescilik"                  ; m2v [18] ="o_her.htm";
m2t [19] ="Hinduizm"                     ; m2v [19] ="o_hin.htm";
m2t [20] ="Hristiyanlýk"                 ; m2v [20] ="o_hri.htm";
m2t [21] ="Ýhvan-üs-safâ"                ; m2v [21] ="o_ihv.htm";
m2t [22] ="Ýslam"                        ; m2v [22] ="o_isl.htm";
m2t [23] ="Janizm"                       ; m2v [23] ="o_jan.htm";
m2t [24] ="Kabbala"                      ; m2v [24] ="o_kab.htm";
m2t [25] ="Konfüçyizm"                   ; m2v [25] ="o_kon.htm";
m2t [26] ="La Porte Church of Christ"    ; m2v [26] ="o_lpcoc.htm";
m2t [27] ="Manicilik"                    ; m2v [27] ="o_man.htm";
m2t [28] ="Mark-age"                     ; m2v [28] ="o_mar.htm";
m2t [29] ="Mitra Kültü"                  ; m2v [29] ="o_mit.htm";
m2t [30] ="Paflikyanlar"                 ; m2v [30] ="o_paf.htm";
m2t [31] ="Rael"                         ; m2v [31] ="o_rael.htm";
m2t [32] ="Sebatay'cýlýk"                ; m2v [32] ="o_seb.htm";
m2t [33] ="Sihizm"                       ; m2v [33] ="o_sih.htm";
m2t [34] ="Swedenborg'culuk"             ; m2v [34] ="o_swe.htm";
m2t [35] ="Þamanizm"                     ; m2v [35] ="o_sam.htm";
m2t [36] ="Þitoizm"                      ; m2v [36] ="o_sit.htm";
m2t [37] ="Taoizm"                       ; m2v [37] ="o_tao.htm";
m2t [38] ="The Church of Uni.and Tri."   ; m2v [38] ="o_tcouat.htm";
m2t [39] ="The House of Yahweh"          ; m2v [39] ="o_thoy.htm";
m2t [40] ="Unarius"                      ; m2v [40] ="o_una.htm";
m2t [41] ="Universal Link"               ; m2v [41] ="o_uni.htm";
m2t [42] ="Yahudilik"                    ; m2v [42] ="o_yah.htm";
m2t [43] ="Yezidilik"                    ; m2v [43] ="o_yez.htm";
m2t [44] ="Zerdüþtlük"                   ; m2v [44] ="o_zer.htm";
m2t [45] = "---------------------------" ; m2v [45] ="bos";
m2t [46] ="<-----"                       ; m2v [46] ="m0";
m2t [47] ="son"                          ; m2v [47] ="son";


m3t [0] ="RUHSAL MESAJLAR"              ; m3v [0] ="bos";
m3t [1] ="----------------"             ; m3v [1] ="bos";
m3t [2] ="Agarta 1. Kitap"              ; m3v [2] ="t_agarta1.htm";
m3t [3] ="Sadýklar Planý"               ; m3v [3] ="t_splani.htm";
m3t [4] ="----------------"             ; m3v [4] ="bos";
m3t [5] ="Albert Pauchard"              ; m3v [5] ="t_ap.htm";
m3t [6] ="Andre Luiz"                   ; m3v [6] ="t_al.htm";
m3t [7] ="Beyaz Kartal"                 ; m3v [7] ="t_bk.htm";
m3t [8] ="Emmanuel"                     ; m3v [8] ="t_em.htm";
m3t [9] ="Kemal Yolcusu"                ; m3v [9] ="t_ky.htm";
m3t [10] ="Kryon"                       ; m3v [10] ="t_kr.htm";
m3t [11] ="----------------"            ; m3v [11] ="bos";
m3t [12] ="<-----"                      ; m3v [12] ="m0";
m3t [13] ="son"                         ; m3v [13] ="son";



m4t [0] ="MAKALELER"                     ; m4v [0] ="bos";
m4t [1] ="------------------"            ; m4v [1] ="bos";
m4t [2] ="Bedri Ruhselman"               ; m4v [2] ="m_brs.htm";
m4t [3] ="Ergün Arýkdal"                 ; m4v [3] ="m_ea.htm";
m4t [4] ="Selman Gerçeksever"            ; m4v [4] ="m_sg.htm";
m4t [5] ="Ö. Cenap Baþman"               ; m4v [5] ="m_ocb.htm";
m4t [6] ="Ýlhan Er"                      ; m4v [6] ="m_ier.htm";
m4t [7] ="Uður Arýdoðan"                 ; m4v [7] ="m_ua.htm";
m4t [8] ="DÝÐER MAKALELER"               ; m4v [8] ="m_d.htm";
m4t [9] = "-----------------"            ; m4v [9] ="bos";
m4t [10] ="<-----"                       ; m4v [10] ="m0";
m4t [11] ="son"                          ; m4v [11] ="son";
